import { NextResponse } from "next/server";
import { getPaymentProvider } from "@/lib/server/payments/mollie";
import { createServiceRoleClient } from "@/lib/supabase/service-role";
import { sendOwnerAlertEmail } from "@/lib/server/email";
import type { PayablePlanId } from "@/lib/server/payments/provider";

export const runtime = "nodejs";

interface MolliePaymentPayload {
  id: string;
  status: string;
  metadata: { userId?: string; planId?: string } | null;
  customerId?: string | null;
  subscriptionId?: string | null;
  sequenceType?: string | null;
}

const FAILURE_STATUSES = new Set(["failed", "expired", "canceled"]);

// Mollie's own "1 month" subscription interval is authoritative for
// *when* the next real charge happens -- this is only the value written
// into current_period_end so the account page and any future access
// gating have something concrete to compare "now" against between
// webhook events. A few hours of drift against Mollie's actual billing
// clock is harmless; being wrong about *whether* a renewal happened
// (the status field) is not, and status is never inferred, only ever
// set from a webhook-verified payment.
const ONE_MONTH_MS = 30 * 24 * 60 * 60 * 1000;

async function countActiveSubscriptions(
  supabase: ReturnType<typeof createServiceRoleClient>
): Promise<number | null> {
  const { count, error } = await supabase
    .from("user_subscriptions")
    .select("id", { count: "exact", head: true })
    .eq("status", "active");
  if (error) {
    console.error("Failed to count active subscriptions:", error);
    return null;
  }
  return count;
}

/**
 * Mollie calls this after every payment status change -- both the
 * original mandate-creating payment from checkout, and every recurring
 * payment a subscription auto-generates afterward (see
 * lib/server/payments/mollie.ts's createSubscription). It is never
 * called by the browser and carries no Supabase session -- everything
 * here runs against the service-role client (bypasses RLS by design,
 * see lib/supabase/service-role.ts), and the payment status itself is
 * re-fetched from Mollie's own API inside handleWebhook, never trusted
 * from the POST body alone.
 */
export async function POST(request: Request): Promise<NextResponse> {
  try {
    const provider = getPaymentProvider();
    const event = await provider.handleWebhook(request);
    const payment = event.raw as MolliePaymentPayload;

    const userId = payment.metadata?.userId;
    const planId = payment.metadata?.planId as PayablePlanId | undefined;
    // Any payment carrying a subscriptionId was generated by the
    // Subscriptions API, not by a fresh checkout -- i.e. it's a renewal,
    // not the mandate-creating first payment. See the metadata note in
    // createSubscription(): subscription metadata (userId/planId) is
    // forwarded onto every payment it generates, so this still resolves
    // the same way a first payment's own metadata does.
    const isRenewal = Boolean(payment.subscriptionId);

    if (!userId || !planId) {
      console.error("Mollie webhook: payment has no userId/planId metadata", payment.id);
      return NextResponse.json({ received: true });
    }

    const supabase = createServiceRoleClient();

    // Idempotency ledger: (provider, event_id) is unique (see
    // supabase/schema.sql). event_id includes the status so each status
    // transition (open -> paid, say) is recorded once, while Mollie
    // re-delivering the *same* transition -- which it can legitimately
    // do -- is a no-op the second time instead of double-processing.
    const { error: ledgerError } = await supabase.from("payment_webhook_events").insert({
      provider: "mollie",
      event_id: `${payment.id}:${payment.status}`,
      event_type: payment.status,
      processed_at: new Date().toISOString(),
    });

    if (ledgerError) {
      // Postgres unique_violation -- this exact (id, status) was already
      // processed. Acknowledge and stop; any other error, log it and
      // return non-200 so Mollie retries the delivery.
      if (ledgerError.code === "23505") {
        return NextResponse.json({ received: true });
      }
      console.error("Failed to record Mollie webhook event:", ledgerError);
      return NextResponse.json({ error: "Failed to record webhook event." }, { status: 500 });
    }

    if (payment.status === "paid") {
      const now = new Date();
      const nowIso = now.toISOString();
      const periodEndIso = new Date(now.getTime() + ONE_MONTH_MS).toISOString();

      if (!isRenewal) {
        // First payment of a new mandate. Create the actual recurring
        // subscription now that Mollie has confirmed the customer
        // authorized future automatic charges -- this is the only place
        // createSubscription() is ever called.
        let subscriptionId: string | null = null;
        if (payment.customerId) {
          try {
            const { origin } = new URL(request.url);
            const subscription = await provider.createSubscription({
              customerId: payment.customerId,
              userId,
              planId,
              webhookUrl: `${origin}/api/payments/webhook`,
            });
            subscriptionId = subscription.id;
          } catch (subError) {
            // The customer WAS charged -- never leave them paying with no
            // plan and no auto-renewal on record. Grant the plan below
            // regardless, log loudly, and alert the owner so this gets a
            // manual subscription set up rather than silently lapsing in
            // 0 days with current_period_end already in the past.
            console.error("Failed to create Mollie subscription after first payment:", subError);
            await sendOwnerAlertEmail({
              subject: "NXTIAI: auto-renewal setup failed for a new Pro subscriber",
              text:
                `A new Pro subscriber (user ${userId}) was charged successfully, but creating ` +
                `the recurring Mollie subscription failed. Their plan has still been activated, ` +
                `but auto-renewal is NOT set up -- check Mollie customer ${payment.customerId} ` +
                `and create the subscription manually, or they will not be billed again.`,
            });
          }
        } else {
          console.error("Mollie webhook: paid first payment has no customerId", payment.id);
        }

        const { error: subError } = await supabase.from("user_subscriptions").upsert(
          {
            user_id: userId,
            provider: "mollie",
            provider_customer_id: payment.customerId ?? null,
            provider_subscription_id: subscriptionId,
            plan_id: planId,
            status: "active",
            current_period_start: nowIso,
            current_period_end: periodEndIso,
            cancel_at_period_end: false,
            updated_at: nowIso,
          },
          { onConflict: "user_id" }
        );
        if (subError) console.error("Failed to update user_subscriptions:", subError);

        const activeCount = await countActiveSubscriptions(supabase);
        await sendOwnerAlertEmail({
          subject: "NXTIAI: new Pro subscriber",
          text:
            `A new Pro subscription just started (auto-renewal active, billed monthly).\n\n` +
            `User: ${userId}\nMollie payment: ${payment.id}\n` +
            (activeCount !== null ? `Active subscriptions now: ${activeCount}\n` : ""),
        });
      } else {
        // Recurring charge succeeded -- extend the period, no other
        // changes needed since the plan was already active.
        const { error: renewError } = await supabase
          .from("user_subscriptions")
          .update({
            status: "active",
            current_period_start: nowIso,
            current_period_end: periodEndIso,
            updated_at: nowIso,
          })
          .eq("user_id", userId);
        if (renewError) console.error("Failed to record renewal in user_subscriptions:", renewError);

        const activeCount = await countActiveSubscriptions(supabase);
        await sendOwnerAlertEmail({
          subject: "NXTIAI: subscription renewed",
          text:
            `A Pro subscription auto-renewed successfully.\n\n` +
            `User: ${userId}\nMollie payment: ${payment.id}\n` +
            (activeCount !== null ? `Active subscriptions now: ${activeCount}\n` : ""),
        });
      }

      // profiles.plan_tier is what the account page and Navbar actually
      // display (see app/account/page.tsx, components/Navbar.tsx) --
      // user_subscriptions above is the detailed billing record, this
      // keeps the two in sync without changing either UI.
      const { error: profileError } = await supabase
        .from("profiles")
        .update({ plan_tier: planId, updated_at: nowIso })
        .eq("id", userId);
      if (profileError) console.error("Failed to update profiles.plan_tier:", profileError);
    } else if (isRenewal && FAILURE_STATUSES.has(payment.status)) {
      // A recurring charge did not go through. Turn the subscription off
      // immediately rather than leaving the customer on Pro with no
      // active payment method backing it: downgrade to free, cancel the
      // Mollie subscription so no further silent charge attempts happen
      // without the customer going through checkout again, and alert the
      // owner right away.
      const nowIso = new Date().toISOString();

      const { error: downgradeError } = await supabase
        .from("user_subscriptions")
        .update({
          status: "past_due",
          updated_at: nowIso,
        })
        .eq("user_id", userId);
      if (downgradeError) console.error("Failed to mark subscription past_due:", downgradeError);

      const { error: profileError } = await supabase
        .from("profiles")
        .update({ plan_tier: "free", updated_at: nowIso })
        .eq("id", userId);
      if (profileError) console.error("Failed to downgrade profiles.plan_tier to free:", profileError);

      if (payment.customerId && payment.subscriptionId) {
        try {
          await provider.cancelSubscription(payment.customerId, payment.subscriptionId);
        } catch (cancelError) {
          // Best-effort -- the customer is already downgraded in our own
          // records regardless. A subscription Mollie still considers
          // "active" on its side but that never charges again because the
          // mandate itself has gone bad is a Mollie-side no-op, not a
          // risk to the customer or to NXTIAI.
          console.error("Failed to cancel Mollie subscription after failed renewal:", cancelError);
        }
      }

      await sendOwnerAlertEmail({
        subject: "NXTIAI: renewal payment failed -- subscriber downgraded automatically",
        text:
          `A Pro subscriber's renewal payment did not go through (status: ${payment.status}).\n\n` +
          `They have been downgraded to Free automatically and their subscription cancelled -- ` +
          `no action needed unless this looks wrong.\n\n` +
          `User: ${userId}\nMollie payment: ${payment.id}\n`,
      });
    }

    return NextResponse.json({ received: true });
  } catch (error) {
    console.error("Mollie webhook handling failed:", error);
    // Non-200 so Mollie retries -- reaching this branch means we
    // couldn't even verify the payment against Mollie's API, not that
    // the payment itself failed.
    return NextResponse.json({ error: "Webhook handling failed." }, { status: 500 });
  }
}
